accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.register_view, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('profile/', views.profile_view, name='profile'), 
    path('profile/delete-image/', views.delete_profile_image, name='delete_profile_image'),
]

cart/urls.py
# cart/urls.py
from django.urls import path
from . import views
app_name = 'cart' 

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('validate/', views.cart_validate, name='cart_validate'),
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include


from ecommerce import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('products/', include('products.urls')),
    path('cart/', include('cart.urls')),
    path('orders/', include('orders.urls')),
    path('accounts/', include('accounts.urls')),
    path('seller/', include('seller.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # cuando se crea un producto nuemo, guarda las imagenes en media url

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('create/', views.create_order, name='create_order'),
    path('mis-ordenes/', views.profile_orders, name='profile_orders'),
    path('created/<int:order_id>/', views.order_created, name='order_created'),
]

products/urls.py
from django.urls import path
from . import views

app_name = 'products' 

urlpatterns = [
    path('', views.product_list, name='product_list'),  
    path('category/<slug:category_slug>/', views.products_by_category, name='products_by_category'),
    path('<int:pk>/', views.product_detail, name='product_detail'),
    path('search-ajax/', views.search_products_ajax, name='search_ajax'),
    path('search/', views.search_results, name='search-results'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css" integrity="sha512-Evv84Mr4kqVGRNSgIGL/F/aIDqQb7xQ2vcrdIwxfjThSH8CSR7PBEakCr51Ck+w+/U6swU2Im1vVX0SVk9ABhg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script src="https://cdn.tailwindcss.com"></script>
    <script>
    tailwind.config = {
        theme: {
        extend: {
            colors: {
            primary: '#F0411D',
            secondary: '#f59e0b',
            },
        },
        },
    }
    </script>
    <title>{% block title %}ELECTRICOS SHOP{% endblock %}</title>    

    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body class="flex flex-col min-h-screen text-gray-800 bg-gray-100">

    <header class="flex flex-col items-center justify-between px-6 py-3 bg-[#FF2424]">
        
        <div class="flex items-center justify-between w-full">

            <div class="flex items-center justify-around w-[40%] gap-4">
                <i class="text-3xl text-yellow-300 fa-solid fa-plug"></i>
                <h1 class="px-4 py-1 text-3xl font-bold text-white">
                    Nacional de Electricos HHH LIDA
                </h1>
            </div>    

        <div class="flex items-center justify-around w-[60%] gap-4 ml-4 text-xl text-white ">                     
                <form id="searchForm" action="{% url 'products:search-results' %}" method="GET" class="flex items-center w-full">
                    <div class="relative w-1/2 flex flex-col">
                        <div class="flex">
                            <input
                                name="q"
                                id="searchInput"
                                class="w-[90%] px-4 py-1 text-black border border-gray-400 rounded-full focus:outline-none"
                                type="text"
                                placeholder="Buscar..."
                                value="{{ query|default:'' }}"
                                autocomplete="off"/>
                            <button type="submit" class="px-4 py-2 text-white rounded-r hover:bg-red-600">
                                <i class="fa-solid fa-magnifying-glass"></i>
                            </button>
                        </div>
                        <div id="searchDropdown" class="hidden absolute top-full left-0 right-0 mt-1 bg-white border border-gray-200 rounded-lg shadow-xl max-h-96 overflow-y-auto z-50"></div>

                    </div>
                </form>

            

            <ul class="flex gap-6 list-none w-1/2" > 
                <a href="{% url 'cart:cart_detail' %}" class="relative hover:underline"><i  class="relative fa-solid fa-cart-shopping"></i>                    
                    {% if request.session.cart %} 
                        <span class="absolute px-2 text-sm text-white bg-red-500 rounded-full -top-2 -right-3">
                            {{ request.session.cart|length }}
                        </span>
                    {% endif %}
                </a>                   
                {% if user.is_authenticated %}                    
                    <!-- <li><span class="text-sm"><i class="fa-solid fa-user"></i> {{ user.username }}</span></li> -->
                    
                    <li><a href="{% url 'accounts:profile' %}" class="hover:text-gray-200">
                        <i class="fa-solid fa-user"> {{ user.username }}</i>
                    </a></li>

                    <li><a href="{% url 'orders:profile_orders' %}" class="hover:text-gray-200">Mis Pedidos</a></li>
                    <li>
                        <form method="post" action="{% url 'accounts:logout' %}">
                            {% csrf_token %}
                            <button type="submit" class="px-3 py-1 text-sm text-white bg-red-500 rounded hover:bg-red-600">Salir</button>
                        </form>
                    </li>

                {% else %}
                    <li><a href="{% url 'accounts:login' %}" class="hover:text-gray-200">Ingresar</a></li>
                    <li><a href="{% url 'accounts:register' %}" class="hover:text-gray-200">Registrarse</a></li>
                {% endif %}    

            </ul> 
        </div>

    </div>
        

        <div class="mt-2">
            <nav class="space-x-20 text-xl">                
                <a href="{% url 'home' %}" class="font-bold hover:underline">Inicio</a>
                <a href="{% url 'products:product_list' %}" class="font-bold hover:underline">Productos</a>
                <a href="{% url 'products:products_by_category' 'cables' %}" class="font-bold hover:underline">Cables</a>
                <a href="{% url 'products:products_by_category' 'tomacorrientes' %}" class="font-bold hover:underline">Tomacorrientes</a>
                <a href="{% url 'products:products_by_category' 'iluminacion' %}" class="font-bold hover:underline">Iluminación</a>                
            </nav>
        </div>
    </header>

    <main class="container flex-grow py-8 mx-auto">

        <!-- bloque que muestra los mensajes de error -->
        {% if messages %}
            
            <!-- //////////////////////////////////////////////////////////////// -->
            <div  id="alerta" role="alert" class="rounded-md border border-gray-300 bg-white shadow-sm mb-10">
                <div class="flex items-start gap-4">                    

                    <div class="flex-1">
                        <p class="mt-0.5 text-sm text-gray-700">
                            <div class="container mt-4">
                                {% for message in messages %}
                                    <div class=" flex {% if message.tags != 'error' %} hidden {% else %}  {% endif %}">                                    
                                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6 text-green-600">
                                            <path stroke-linecap="round" stroke-linejoin="round" d="M9 12.75L11.25 15 15 9.75M21 12a9 9 0 11-18 0 9 9 0 0118 0z"></path>
                                         </svg>
                                        <strong class="font-medium text-gray-900"> Sin Stock !</strong>
                                    </div>

                                    <div class="p-3 mb-3 text-gray-700 font-bold rounded 
                                        {% if message.tags == 'error' %}  bg-red-500 {% else %} bg-green-500 {% endif %}">
                                        {{ message }}
                                    </div>
                                {% endfor %}
                            </div>

                        </p>
                    </div>

                    <button id="cerrar" class="-m-3 rounded-full p-3.5 text-gray-500 transition-colors hover:bg-gray-50 hover:text-gray-700" type="button" aria-label="Dismiss alert">
                    <span class="sr-only">Dismiss popup</span>

                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-5">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12"></path>
                    </svg>
                    </button>
                </div>
            </div>
            
        {% endif %}


        {% block content %}{% endblock %}

    
    </main>

    <footer class="py-4 mt-auto text-center text-white bg-gray-800">
        <p>© 2025 Mi Ecommerce</p>
    </footer>

    <script src="{% static 'js/main.js' %}"></script>
</body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block title %}Inicio | Nacional de Electricos{% endblock %}

{% block content %}

{% load static%} 
<!-- carga los archivos de la carpeta static -->

<section class="py-16 text-white bg-gradient-to-r from-[#FF2424] to-red-500">
  <div class="container mx-auto text-center">
    <h1 class="mb-4 text-4xl font-bold">Bienvenido a <span class="text-black">Nacional de Electricos HHH LIDA</span></h1>
    <p class="mb-6 text-lg">Tu tienda de confianza en productos eléctricos, iluminación y herramientas.</p>
    <a href="{% url 'products:product_list' %}" class="px-6 py-3 font-semibold text-black bg-white rounded hover:bg-red-600">
      Ver Productos
    </a>
  </div>
</section>


<section class="py-12 bg-gray-100">
  <div class="container mx-auto text-center">
    <h2 class="mb-8 text-3xl font-bold text-gray-800">Categorías destacadas</h2>

    <div class="grid grid-cols-1 gap-6 sm:grid-cols-3 md:grid-cols-3 lg:grid-cols-3">
       
    <a href="{% url 'products:products_by_category' 'iluminacion' %}">
        <div class="object-cover p-6 bg-white rounded-lg shadow hover:shadow-lg">
            <div class="w-full h-48 overflow-hidden rounded-lg">
                    <img src="{% static 'img/iluminacion.jpeg' %}" 
                         alt="Iluminación" 
                         class="object-cover w-full h-full">
            </div>
            <h3 class="text-xl font-semibold text-gray-800">Iluminación</h3>
            <p class="mt-2 text-gray-600">Bombillos, lámparas LED y más.</p>
        </div>
      </a>

    <a href="{% url 'products:products_by_category' 'cables' %}">    
      <div class="object-cover p-6 bg-white rounded-lg shadow hover:shadow-lg">
        <div class="w-full h-48 overflow-hidden rounded-lg">
                    <img src="{% static 'img/cable.jpg' %}" 
                         alt="Iluminación" 
                         class="object-cover w-full h-full">
                </div>
        <h3 class="text-xl font-semibold text-gray-800">Cableado</h3>
        <p class="mt-2 text-gray-600">Cables, conectores y canaletas.</p>
      </div>
    </a>
    
    <a href="{% url 'products:products_by_category' 'tomacorrientes' %}">
      <div class="p-6 bg-white rounded-lg shadow hover:shadow-lg">
        <div class="w-full h-48 overflow-hidden rounded-lg">
                    <img src="{% static 'img/tomacorriente.avif' %}" 
                         alt="Iluminación" 
                         class="object-cover w-full h-full">
        </div>
        <h3 class="text-xl font-semibold text-gray-800">Tomacorrientes</h3>
        <p class="mt-2 text-gray-600">Todo para tus instalaciones.</p>
      </div>
      
    </div>
   
    
    
    
  </div>
</section>

<!-- Sección de información -->
<section class="py-16 bg-white">
  <div class="container mx-auto text-center">
    <h2 class="mb-6 text-3xl font-bold text-gray-800">¿Por qué elegirnos?</h2>
    <div class="grid grid-cols-1 gap-6 md:grid-cols-3">
      <div class="p-6">
        <h3 class="mb-2 text-xl font-semibold text-blue-700">🔌 Calidad garantizada</h3>
        <p class="text-gray-600">Solo trabajamos con marcas certificadas y productos duraderos.</p>
      </div>
      <div class="p-6">
        <h3 class="mb-2 text-xl font-semibold text-blue-700">⚡ Entrega rápida</h3>
        <p class="text-gray-600">Recibe tus productos en menos de 48 horas en todo el país.</p>
      </div>
      <div class="p-6">
        <h3 class="mb-2 text-xl font-semibold text-blue-700">💬 Soporte personalizado</h3>
        <p class="text-gray-600">Te asesoramos en tus compras y proyectos eléctricos.</p>
      </div>
    </div>
  </div>
</section>

{% endblock %}